"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* eslint-disable */
const metadata = {
    fields: {
        example: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, createdAt: {
                name: "createdAt",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, updatedAt: {
                name: "updatedAt",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@updatedAt", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        release: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, xoVersion: {
                name: "xoVersion",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, build: {
                name: "build",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, description: {
                name: "description",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, battlePass: {
                name: "battlePass",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, url: {
                name: "url",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, startDate: {
                name: "startDate",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, endDate: {
                name: "endDate",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, active: {
                name: "active",
                type: "Boolean",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, itemStats: {
                name: "itemStats",
                type: "ItemStats",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'release',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, recipes: {
                name: "recipes",
                type: "Recipe",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'release',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, packs: {
                name: "packs",
                type: "Pack",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'release',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        recipe: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, result: {
                name: "result",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'recipes',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "resultItemId" }
            }, resultItemId: {
                name: "resultItemId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, quantity: {
                name: "quantity",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, release: {
                name: "release",
                type: "Release",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: 'recipes',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "releaseId" }
            }, releaseId: {
                name: "releaseId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, craftCost: {
                name: "craftCost",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, timestamp: {
                name: "timestamp",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, active: {
                name: "active",
                type: "Boolean",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, ingredients: {
                name: "ingredients",
                type: "RecipeItem",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'recipe',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        recipeItem: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, recipe: {
                name: "recipe",
                type: "Recipe",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'ingredients',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "recipeId" }
            }, recipeId: {
                name: "recipeId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, item: {
                name: "item",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'recipeItems',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "itemId" }
            }, itemId: {
                name: "itemId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, quantity: {
                name: "quantity",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        pack: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, description: {
                name: "description",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, steamAppID: {
                name: "steamAppID",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, key: {
                name: "key",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, coins: {
                name: "coins",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, release: {
                name: "release",
                type: "Release",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: 'packs',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "releaseId" }
            }, releaseId: {
                name: "releaseId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, active: {
                name: "active",
                type: "Boolean",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, items: {
                name: "items",
                type: "PackItem",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'pack',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, packPrices: {
                name: "packPrices",
                type: "PackPrice",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'pack',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        packItem: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, pack: {
                name: "pack",
                type: "Pack",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'items',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "packId" }
            }, packId: {
                name: "packId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, item: {
                name: "item",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'packItems',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "itemId" }
            }, itemId: {
                name: "itemId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, quantity: {
                name: "quantity",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        packPrice: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, pack: {
                name: "pack",
                type: "Pack",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'packPrices',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "packId" }
            }, packId: {
                name: "packId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, timestamp: {
                name: "timestamp",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, priceUSD: {
                name: "priceUSD",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, priceEUR: {
                name: "priceEUR",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, priceGBP: {
                name: "priceGBP",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, priceRUB: {
                name: "priceRUB",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, discount: {
                name: "discount",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        category: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, items: {
                name: "items",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'category',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        faction: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, items: {
                name: "items",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'faction',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        type: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, items: {
                name: "items",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'type',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        rarity: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, order: {
                name: "order",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, primaryColor: {
                name: "primaryColor",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, secondaryColor: {
                name: "secondaryColor",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, items: {
                name: "items",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'rarity',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        item: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, marketDef: {
                name: "marketDef",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [{ "name": "@omit", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, quantity: {
                name: "quantity",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, type: {
                name: "type",
                type: "Type",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'items',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "typeId" }
            }, typeId: {
                name: "typeId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, category: {
                name: "category",
                type: "Category",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'items',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "categoryId" }
            }, categoryId: {
                name: "categoryId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, faction: {
                name: "faction",
                type: "Faction",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'items',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "factionId" }
            }, factionId: {
                name: "factionId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, rarity: {
                name: "rarity",
                type: "Rarity",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'items',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "rarityId" }
            }, rarityId: {
                name: "rarityId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, level: {
                name: "level",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, sellPriceMin: {
                name: "sellPriceMin",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, sellOrders: {
                name: "sellOrders",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, buyPriceMax: {
                name: "buyPriceMax",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, buyOrders: {
                name: "buyOrders",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, craftCost: {
                name: "craftCost",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, timestamp: {
                name: "timestamp",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, active: {
                name: "active",
                type: "Boolean",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, logId: {
                name: "logId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, itemStats: {
                name: "itemStats",
                type: "ItemStats",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'item',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, market: {
                name: "market",
                type: "Market",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'item',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, badgeExchange: {
                name: "badgeExchange",
                type: "BadgeExchange",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'item',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, recipes: {
                name: "recipes",
                type: "Recipe",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'result',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, recipeItems: {
                name: "recipeItems",
                type: "RecipeItem",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'item',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, packItems: {
                name: "packItems",
                type: "PackItem",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'item',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, itemSynergies: {
                name: "itemSynergies",
                type: "SynergyItem",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'item',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        itemStats: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, item: {
                name: "item",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'itemStats',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "itemId" }
            }, itemId: {
                name: "itemId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, user: {
                name: "user",
                type: "User",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'itemStats',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "userId" }
            }, userId: {
                name: "userId",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, release: {
                name: "release",
                type: "Release",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: 'itemStats',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "releaseId" }
            }, releaseId: {
                name: "releaseId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, timestamp: {
                name: "timestamp",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, description: {
                name: "description",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, increasesDurability: {
                name: "increasesDurability",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, increasesReputationPercent: {
                name: "increasesReputationPercent",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, topSpeed: {
                name: "topSpeed",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, ps: {
                name: "ps",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, damage: {
                name: "damage",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, fireRate: {
                name: "fireRate",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, range: {
                name: "range",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, accuracy: {
                name: "accuracy",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, timeToOverheating: {
                name: "timeToOverheating",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, maxAmmo: {
                name: "maxAmmo",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, blastPower: {
                name: "blastPower",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, addsEnergy: {
                name: "addsEnergy",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, tonnage: {
                name: "tonnage",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, massLimit: {
                name: "massLimit",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, maxCabinSpeed: {
                name: "maxCabinSpeed",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, maxChassisSpeed: {
                name: "maxChassisSpeed",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, power: {
                name: "power",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, cabinPower: {
                name: "cabinPower",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, fuelReserves: {
                name: "fuelReserves",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, featureBulletPercent: {
                name: "featureBulletPercent",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, featureMeleePercent: {
                name: "featureMeleePercent",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, featureBlastPercent: {
                name: "featureBlastPercent",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, featureFirePercent: {
                name: "featureFirePercent",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, featurePassthroughPercent: {
                name: "featurePassthroughPercent",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, durability: {
                name: "durability",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, energyDrain: {
                name: "energyDrain",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, mass: {
                name: "mass",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, perks: {
                name: "perks",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        synergy: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, synergyItems: {
                name: "synergyItems",
                type: "SynergyItem",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'synergy',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        synergyItem: {
            synergy: {
                name: "synergy",
                type: "Synergy",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'synergyItems',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "synergyId" }
            }, synergyId: {
                name: "synergyId",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, item: {
                name: "item",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'itemSynergies',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "itemId" }
            }, itemId: {
                name: "itemId",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            },
        },
        market: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, item: {
                name: "item",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'market',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "itemId" }
            }, itemId: {
                name: "itemId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, marketDef: {
                name: "marketDef",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, sellPriceMin: {
                name: "sellPriceMin",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, sellOrders: {
                name: "sellOrders",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, buyPriceMax: {
                name: "buyPriceMax",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, buyOrders: {
                name: "buyOrders",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, craftCost: {
                name: "craftCost",
                type: "Float",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, timestamp: {
                name: "timestamp",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        badgeExchange: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, item: {
                name: "item",
                type: "Item",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'badgeExchange',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "itemId" }
            }, itemId: {
                name: "itemId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, quantity: {
                name: "quantity",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, badges: {
                name: "badges",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, active: {
                name: "active",
                type: "Boolean",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, timestamp: {
                name: "timestamp",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        log: {
            id: {
                name: "id",
                type: "Int",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, timestamp: {
                name: "timestamp",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, user: {
                name: "user",
                type: "User",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'log',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "userId" }
            }, userId: {
                name: "userId",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, tableChanged: {
                name: "tableChanged",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, recordId: {
                name: "recordId",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, record: {
                name: "record",
                type: "Json",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        account: {
            id: {
                name: "id",
                type: "String",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, userId: {
                name: "userId",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, type: {
                name: "type",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, provider: {
                name: "provider",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, providerAccountId: {
                name: "providerAccountId",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, refresh_token: {
                name: "refresh_token",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, access_token: {
                name: "access_token",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, expires_at: {
                name: "expires_at",
                type: "Int",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, token_type: {
                name: "token_type",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, scope: {
                name: "scope",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, id_token: {
                name: "id_token",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, session_state: {
                name: "session_state",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, user: {
                name: "user",
                type: "User",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'accounts',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "userId" }
            },
        },
        session: {
            id: {
                name: "id",
                type: "String",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, sessionToken: {
                name: "sessionToken",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@unique", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, userId: {
                name: "userId",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: true,
                foreignKeyMapping: undefined
            }, expires: {
                name: "expires",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, user: {
                name: "user",
                type: "User",
                isId: false,
                isDataModel: true,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: 'sessions',
                isRelationOwner: true,
                isForeignKey: false,
                foreignKeyMapping: { "id": "userId" }
            },
        },
        user: {
            id: {
                name: "id",
                type: "String",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@id", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, name: {
                name: "name",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, role: {
                name: "role",
                type: "UserRole",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, email: {
                name: "email",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [{ "name": "@unique", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, emailVerified: {
                name: "emailVerified",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, image: {
                name: "image",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: true,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, accounts: {
                name: "accounts",
                type: "Account",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, sessions: {
                name: "sessions",
                type: "Session",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, itemStats: {
                name: "itemStats",
                type: "ItemStats",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, log: {
                name: "log",
                type: "log",
                isId: false,
                isDataModel: true,
                isArray: true,
                isOptional: false,
                attributes: [],
                backLink: 'user',
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
        verificationToken: {
            identifier: {
                name: "identifier",
                type: "String",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, token: {
                name: "token",
                type: "String",
                isId: true,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [{ "name": "@unique", "args": [] }],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            }, expires: {
                name: "expires",
                type: "DateTime",
                isId: false,
                isDataModel: false,
                isArray: false,
                isOptional: false,
                attributes: [],
                backLink: undefined,
                isRelationOwner: false,
                isForeignKey: false,
                foreignKeyMapping: undefined
            },
        },
    },
    uniqueConstraints: {
        example: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        release: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        recipe: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        recipeItem: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        pack: {
            steamAppID: {
                name: "steamAppID",
                fields: ["steamAppID"]
            }, id: {
                name: "id",
                fields: ["id"]
            },
        },
        packItem: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        packPrice: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        category: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        faction: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        type: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        rarity: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        item: {
            marketDef: {
                name: "marketDef",
                fields: ["marketDef"]
            }, id: {
                name: "id",
                fields: ["id"]
            },
        },
        itemStats: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        synergy: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        synergyItem: {
            synergyId_itemId: {
                name: "synergyId_itemId",
                fields: ["synergyId", "itemId"]
            },
        },
        market: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        badgeExchange: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        log: {
            id: {
                name: "id",
                fields: ["id"]
            },
        },
        account: {
            provider_providerAccountId: {
                name: "provider_providerAccountId",
                fields: ["provider", "providerAccountId"]
            }, id: {
                name: "id",
                fields: ["id"]
            },
        },
        session: {
            id: {
                name: "id",
                fields: ["id"]
            }, sessionToken: {
                name: "sessionToken",
                fields: ["sessionToken"]
            },
        },
        user: {
            id: {
                name: "id",
                fields: ["id"]
            }, email: {
                name: "email",
                fields: ["email"]
            },
        },
        verificationToken: {
            identifier_token: {
                name: "identifier_token",
                fields: ["identifier", "token"]
            }, token: {
                name: "token",
                fields: ["token"]
            },
        },
    },
};
exports.default = metadata;
