-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "buyOrders" INTEGER,
ADD COLUMN     "buyPriceMax" DOUBLE PRECISION,
ADD COLUMN     "sellOrders" INTEGER,
ADD COLUMN     "sellPriceMin" DOUBLE PRECISION,
ADD COLUMN     "timestamp" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Recipe" ADD COLUMN     "craftCost" DOUBLE PRECISION,
ADD COLUMN     "timestamp" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
