import { z } from 'zod';
export declare const AccountSchema: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodString;
    provider: z.ZodString;
    providerAccountId: z.ZodString;
    refresh_token: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    access_token: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    expires_at: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    token_type: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    scope: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    id_token: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    session_state: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    type: string;
    id: string;
    provider: string;
    providerAccountId: string;
    refresh_token?: string | null | undefined;
    access_token?: string | null | undefined;
    expires_at?: number | null | undefined;
    token_type?: string | null | undefined;
    scope?: string | null | undefined;
    id_token?: string | null | undefined;
    session_state?: string | null | undefined;
}, {
    type: string;
    id: string;
    provider: string;
    providerAccountId: string;
    refresh_token?: string | null | undefined;
    access_token?: string | null | undefined;
    expires_at?: number | null | undefined;
    token_type?: string | null | undefined;
    scope?: string | null | undefined;
    id_token?: string | null | undefined;
    session_state?: string | null | undefined;
}>;
export declare const AccountCreateSchema: z.ZodObject<{
    type: z.ZodString;
    id: z.ZodOptional<z.ZodString>;
    provider: z.ZodString;
    providerAccountId: z.ZodString;
    refresh_token: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    access_token: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    expires_at: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    token_type: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    scope: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    id_token: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    session_state: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    type: string;
    provider: string;
    providerAccountId: string;
    id?: string | undefined;
    refresh_token?: string | null | undefined;
    access_token?: string | null | undefined;
    expires_at?: number | null | undefined;
    token_type?: string | null | undefined;
    scope?: string | null | undefined;
    id_token?: string | null | undefined;
    session_state?: string | null | undefined;
}, {
    type: string;
    provider: string;
    providerAccountId: string;
    id?: string | undefined;
    refresh_token?: string | null | undefined;
    access_token?: string | null | undefined;
    expires_at?: number | null | undefined;
    token_type?: string | null | undefined;
    scope?: string | null | undefined;
    id_token?: string | null | undefined;
    session_state?: string | null | undefined;
}>;
export declare const AccountUpdateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    provider: z.ZodOptional<z.ZodString>;
    providerAccountId: z.ZodOptional<z.ZodString>;
    refresh_token: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    access_token: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    expires_at: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    token_type: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    scope: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    id_token: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    session_state: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
}, "strip", z.ZodTypeAny, {
    id?: string | undefined;
    type?: string | undefined;
    provider?: string | undefined;
    providerAccountId?: string | undefined;
    refresh_token?: string | null | undefined;
    access_token?: string | null | undefined;
    expires_at?: number | null | undefined;
    token_type?: string | null | undefined;
    scope?: string | null | undefined;
    id_token?: string | null | undefined;
    session_state?: string | null | undefined;
}, {
    id?: string | undefined;
    type?: string | undefined;
    provider?: string | undefined;
    providerAccountId?: string | undefined;
    refresh_token?: string | null | undefined;
    access_token?: string | null | undefined;
    expires_at?: number | null | undefined;
    token_type?: string | null | undefined;
    scope?: string | null | undefined;
    id_token?: string | null | undefined;
    session_state?: string | null | undefined;
}>;
