import { z } from 'zod';
export declare const ItemSchema: z.ZodObject<Omit<{
    id: z.ZodNumber;
    name: z.ZodString;
    marketDef: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    quantity: z.ZodNumber;
    level: z.ZodNumber;
    sellPriceMin: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    sellOrders: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    buyPriceMax: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    buyOrders: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    craftCost: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    timestamp: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    active: z.ZodBoolean;
    logId: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
}, "marketDef">, "strip", z.ZodTypeAny, {
    id: number;
    name: string;
    active: boolean;
    quantity: number;
    level: number;
    craftCost?: number | null | undefined;
    timestamp?: Date | null | undefined;
    sellPriceMin?: number | null | undefined;
    sellOrders?: number | null | undefined;
    buyPriceMax?: number | null | undefined;
    buyOrders?: number | null | undefined;
    logId?: number | null | undefined;
}, {
    id: number;
    name: string;
    active: boolean;
    quantity: number;
    level: number;
    craftCost?: number | null | undefined;
    timestamp?: Date | null | undefined;
    sellPriceMin?: number | null | undefined;
    sellOrders?: number | null | undefined;
    buyPriceMax?: number | null | undefined;
    buyOrders?: number | null | undefined;
    logId?: number | null | undefined;
}>;
export declare const ItemCreateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    name: z.ZodString;
    active: z.ZodBoolean;
    quantity: z.ZodNumber;
    craftCost: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    timestamp: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodDate>>>;
    marketDef: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    level: z.ZodNumber;
    sellPriceMin: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    sellOrders: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    buyPriceMax: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    buyOrders: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    logId: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    name: string;
    active: boolean;
    quantity: number;
    level: number;
    id?: number | undefined;
    craftCost?: number | null | undefined;
    timestamp?: Date | null | undefined;
    marketDef?: string | null | undefined;
    sellPriceMin?: number | null | undefined;
    sellOrders?: number | null | undefined;
    buyPriceMax?: number | null | undefined;
    buyOrders?: number | null | undefined;
    logId?: number | null | undefined;
}, {
    name: string;
    active: boolean;
    quantity: number;
    level: number;
    id?: number | undefined;
    craftCost?: number | null | undefined;
    timestamp?: Date | null | undefined;
    marketDef?: string | null | undefined;
    sellPriceMin?: number | null | undefined;
    sellOrders?: number | null | undefined;
    buyPriceMax?: number | null | undefined;
    buyOrders?: number | null | undefined;
    logId?: number | null | undefined;
}>;
export declare const ItemUpdateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    name: z.ZodOptional<z.ZodString>;
    marketDef: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    quantity: z.ZodOptional<z.ZodNumber>;
    level: z.ZodOptional<z.ZodNumber>;
    sellPriceMin: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    sellOrders: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    buyPriceMax: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    buyOrders: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    craftCost: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    timestamp: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodDate>>>;
    active: z.ZodOptional<z.ZodBoolean>;
    logId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
}, "strip", z.ZodTypeAny, {
    id?: number | undefined;
    name?: string | undefined;
    marketDef?: string | null | undefined;
    quantity?: number | undefined;
    level?: number | undefined;
    sellPriceMin?: number | null | undefined;
    sellOrders?: number | null | undefined;
    buyPriceMax?: number | null | undefined;
    buyOrders?: number | null | undefined;
    craftCost?: number | null | undefined;
    timestamp?: Date | null | undefined;
    active?: boolean | undefined;
    logId?: number | null | undefined;
}, {
    id?: number | undefined;
    name?: string | undefined;
    marketDef?: string | null | undefined;
    quantity?: number | undefined;
    level?: number | undefined;
    sellPriceMin?: number | null | undefined;
    sellOrders?: number | null | undefined;
    buyPriceMax?: number | null | undefined;
    buyOrders?: number | null | undefined;
    craftCost?: number | null | undefined;
    timestamp?: Date | null | undefined;
    active?: boolean | undefined;
    logId?: number | null | undefined;
}>;
