import { z } from 'zod';
export declare const ItemStatsSchema: z.ZodObject<{
    id: z.ZodNumber;
    timestamp: z.ZodDate;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    increasesDurability: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    increasesReputationPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    topSpeed: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    ps: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    damage: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    fireRate: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    range: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    accuracy: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    timeToOverheating: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    maxAmmo: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    blastPower: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    addsEnergy: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    tonnage: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    massLimit: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    maxCabinSpeed: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    maxChassisSpeed: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    power: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    cabinPower: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    fuelReserves: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featureBulletPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featureMeleePercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featureBlastPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featureFirePercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featurePassthroughPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    durability: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    energyDrain: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    mass: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    perks: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id: number;
    timestamp: Date;
    description?: string | null | undefined;
    increasesDurability?: number | null | undefined;
    increasesReputationPercent?: number | null | undefined;
    topSpeed?: number | null | undefined;
    ps?: number | null | undefined;
    damage?: number | null | undefined;
    fireRate?: number | null | undefined;
    range?: number | null | undefined;
    accuracy?: number | null | undefined;
    timeToOverheating?: number | null | undefined;
    maxAmmo?: number | null | undefined;
    blastPower?: number | null | undefined;
    addsEnergy?: number | null | undefined;
    tonnage?: number | null | undefined;
    massLimit?: number | null | undefined;
    maxCabinSpeed?: number | null | undefined;
    maxChassisSpeed?: number | null | undefined;
    power?: number | null | undefined;
    cabinPower?: number | null | undefined;
    fuelReserves?: number | null | undefined;
    featureBulletPercent?: number | null | undefined;
    featureMeleePercent?: number | null | undefined;
    featureBlastPercent?: number | null | undefined;
    featureFirePercent?: number | null | undefined;
    featurePassthroughPercent?: number | null | undefined;
    durability?: number | null | undefined;
    energyDrain?: number | null | undefined;
    mass?: number | null | undefined;
    perks?: string | null | undefined;
}, {
    id: number;
    timestamp: Date;
    description?: string | null | undefined;
    increasesDurability?: number | null | undefined;
    increasesReputationPercent?: number | null | undefined;
    topSpeed?: number | null | undefined;
    ps?: number | null | undefined;
    damage?: number | null | undefined;
    fireRate?: number | null | undefined;
    range?: number | null | undefined;
    accuracy?: number | null | undefined;
    timeToOverheating?: number | null | undefined;
    maxAmmo?: number | null | undefined;
    blastPower?: number | null | undefined;
    addsEnergy?: number | null | undefined;
    tonnage?: number | null | undefined;
    massLimit?: number | null | undefined;
    maxCabinSpeed?: number | null | undefined;
    maxChassisSpeed?: number | null | undefined;
    power?: number | null | undefined;
    cabinPower?: number | null | undefined;
    fuelReserves?: number | null | undefined;
    featureBulletPercent?: number | null | undefined;
    featureMeleePercent?: number | null | undefined;
    featureBlastPercent?: number | null | undefined;
    featureFirePercent?: number | null | undefined;
    featurePassthroughPercent?: number | null | undefined;
    durability?: number | null | undefined;
    energyDrain?: number | null | undefined;
    mass?: number | null | undefined;
    perks?: string | null | undefined;
}>;
export declare const ItemStatsCreateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    description: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    timestamp: z.ZodOptional<z.ZodDate>;
    increasesDurability: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    increasesReputationPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    topSpeed: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    ps: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    damage: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    fireRate: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    range: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    accuracy: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    timeToOverheating: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    maxAmmo: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    blastPower: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    addsEnergy: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    tonnage: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    massLimit: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    maxCabinSpeed: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    maxChassisSpeed: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    power: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    cabinPower: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    fuelReserves: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featureBulletPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featureMeleePercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featureBlastPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featureFirePercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    featurePassthroughPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    durability: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    energyDrain: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    mass: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    perks: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: number | undefined;
    description?: string | null | undefined;
    timestamp?: Date | undefined;
    increasesDurability?: number | null | undefined;
    increasesReputationPercent?: number | null | undefined;
    topSpeed?: number | null | undefined;
    ps?: number | null | undefined;
    damage?: number | null | undefined;
    fireRate?: number | null | undefined;
    range?: number | null | undefined;
    accuracy?: number | null | undefined;
    timeToOverheating?: number | null | undefined;
    maxAmmo?: number | null | undefined;
    blastPower?: number | null | undefined;
    addsEnergy?: number | null | undefined;
    tonnage?: number | null | undefined;
    massLimit?: number | null | undefined;
    maxCabinSpeed?: number | null | undefined;
    maxChassisSpeed?: number | null | undefined;
    power?: number | null | undefined;
    cabinPower?: number | null | undefined;
    fuelReserves?: number | null | undefined;
    featureBulletPercent?: number | null | undefined;
    featureMeleePercent?: number | null | undefined;
    featureBlastPercent?: number | null | undefined;
    featureFirePercent?: number | null | undefined;
    featurePassthroughPercent?: number | null | undefined;
    durability?: number | null | undefined;
    energyDrain?: number | null | undefined;
    mass?: number | null | undefined;
    perks?: string | null | undefined;
}, {
    id?: number | undefined;
    description?: string | null | undefined;
    timestamp?: Date | undefined;
    increasesDurability?: number | null | undefined;
    increasesReputationPercent?: number | null | undefined;
    topSpeed?: number | null | undefined;
    ps?: number | null | undefined;
    damage?: number | null | undefined;
    fireRate?: number | null | undefined;
    range?: number | null | undefined;
    accuracy?: number | null | undefined;
    timeToOverheating?: number | null | undefined;
    maxAmmo?: number | null | undefined;
    blastPower?: number | null | undefined;
    addsEnergy?: number | null | undefined;
    tonnage?: number | null | undefined;
    massLimit?: number | null | undefined;
    maxCabinSpeed?: number | null | undefined;
    maxChassisSpeed?: number | null | undefined;
    power?: number | null | undefined;
    cabinPower?: number | null | undefined;
    fuelReserves?: number | null | undefined;
    featureBulletPercent?: number | null | undefined;
    featureMeleePercent?: number | null | undefined;
    featureBlastPercent?: number | null | undefined;
    featureFirePercent?: number | null | undefined;
    featurePassthroughPercent?: number | null | undefined;
    durability?: number | null | undefined;
    energyDrain?: number | null | undefined;
    mass?: number | null | undefined;
    perks?: string | null | undefined;
}>;
export declare const ItemStatsUpdateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodOptional<z.ZodDate>;
    description: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    increasesDurability: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    increasesReputationPercent: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    topSpeed: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    ps: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    damage: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    fireRate: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    range: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    accuracy: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    timeToOverheating: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    maxAmmo: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    blastPower: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    addsEnergy: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    tonnage: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    massLimit: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    maxCabinSpeed: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    maxChassisSpeed: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    power: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    cabinPower: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    fuelReserves: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    featureBulletPercent: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    featureMeleePercent: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    featureBlastPercent: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    featureFirePercent: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    featurePassthroughPercent: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    durability: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    energyDrain: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    mass: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
    perks: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
}, "strip", z.ZodTypeAny, {
    id?: number | undefined;
    timestamp?: Date | undefined;
    description?: string | null | undefined;
    increasesDurability?: number | null | undefined;
    increasesReputationPercent?: number | null | undefined;
    topSpeed?: number | null | undefined;
    ps?: number | null | undefined;
    damage?: number | null | undefined;
    fireRate?: number | null | undefined;
    range?: number | null | undefined;
    accuracy?: number | null | undefined;
    timeToOverheating?: number | null | undefined;
    maxAmmo?: number | null | undefined;
    blastPower?: number | null | undefined;
    addsEnergy?: number | null | undefined;
    tonnage?: number | null | undefined;
    massLimit?: number | null | undefined;
    maxCabinSpeed?: number | null | undefined;
    maxChassisSpeed?: number | null | undefined;
    power?: number | null | undefined;
    cabinPower?: number | null | undefined;
    fuelReserves?: number | null | undefined;
    featureBulletPercent?: number | null | undefined;
    featureMeleePercent?: number | null | undefined;
    featureBlastPercent?: number | null | undefined;
    featureFirePercent?: number | null | undefined;
    featurePassthroughPercent?: number | null | undefined;
    durability?: number | null | undefined;
    energyDrain?: number | null | undefined;
    mass?: number | null | undefined;
    perks?: string | null | undefined;
}, {
    id?: number | undefined;
    timestamp?: Date | undefined;
    description?: string | null | undefined;
    increasesDurability?: number | null | undefined;
    increasesReputationPercent?: number | null | undefined;
    topSpeed?: number | null | undefined;
    ps?: number | null | undefined;
    damage?: number | null | undefined;
    fireRate?: number | null | undefined;
    range?: number | null | undefined;
    accuracy?: number | null | undefined;
    timeToOverheating?: number | null | undefined;
    maxAmmo?: number | null | undefined;
    blastPower?: number | null | undefined;
    addsEnergy?: number | null | undefined;
    tonnage?: number | null | undefined;
    massLimit?: number | null | undefined;
    maxCabinSpeed?: number | null | undefined;
    maxChassisSpeed?: number | null | undefined;
    power?: number | null | undefined;
    cabinPower?: number | null | undefined;
    fuelReserves?: number | null | undefined;
    featureBulletPercent?: number | null | undefined;
    featureMeleePercent?: number | null | undefined;
    featureBlastPercent?: number | null | undefined;
    featureFirePercent?: number | null | undefined;
    featurePassthroughPercent?: number | null | undefined;
    durability?: number | null | undefined;
    energyDrain?: number | null | undefined;
    mass?: number | null | undefined;
    perks?: string | null | undefined;
}>;
