import { z } from 'zod';

export const ItemStatsScalarFieldEnumSchema = z.enum([
  'id',
  'itemId',
  'userId',
  'releaseId',
  'timestamp',
  'description',
  'increasesDurability',
  'increasesReputationPercent',
  'topSpeed',
  'ps',
  'damage',
  'fireRate',
  'range',
  'accuracy',
  'timeToOverheating',
  'maxAmmo',
  'blastPower',
  'addsEnergy',
  'tonnage',
  'massLimit',
  'maxCabinSpeed',
  'maxChassisSpeed',
  'power',
  'cabinPower',
  'fuelReserves',
  'featureBulletPercent',
  'featureMeleePercent',
  'featureBlastPercent',
  'featureFirePercent',
  'featurePassthroughPercent',
  'durability',
  'energyDrain',
  'mass',
  'perks',
]);
